import { Primer, Polymerase, BufferReagent, ChemistryReagent, KnowledgeItem, ProtocolStep, CyclerHardwarePreset, TraceabilitySource } from '../types/pcr';

export const HARDWARE_PRESETS: CyclerHardwarePreset[] = [
  {
    id: 'preset_standard_96',
    name: 'Termociclador Estándar 96 Pocillos (Rampa 3.0 °C/s)',
    rampRateHeating: 3.0,
    rampRateCooling: 2.5,
    format: '96_well',
    lidTemp: 105,
  },
  {
    id: 'preset_fast_96',
    name: 'Termociclador Fast PCR Peltier (Rampa 5.0 °C/s)',
    rampRateHeating: 5.0,
    rampRateCooling: 4.5,
    format: '96_well',
    lidTemp: 105,
  },
  {
    id: 'preset_qpcr_optical',
    name: 'Termociclador qPCR Óptico con Detector Láser/CCD',
    rampRateHeating: 4.0,
    rampRateCooling: 3.0,
    format: '96_well',
    lidTemp: 105,
  },
];

export const DEMO_PRIMERS: Primer[] = [
  {
    id: 'primer_a_fwd',
    name: 'Primer A (Fwd GAPDH-Exon2)',
    direction: 'forward',
    sequence: '5\'-GGTCTCCTCTGACTTCAACA-3\'',
    length: 20,
    gcPercent: 50.0,
    tmCalculated: 60.2,
    tmOrigin: 'CALCULATED',
    recommendedAnnealing: 60.0,
    annealingOrigin: 'REFERENCE',
    sourceDocument: 'Protocolo de Referencia Bio-Mol GAPDH-01 (Demo Data)',
    targetGene: 'GAPDH Humano',
  },
  {
    id: 'primer_b_rev',
    name: 'Primer B (Rev GAPDH-Exon3)',
    direction: 'reverse',
    sequence: '5\'-AGGGGAGATTCAGTGTGGTG-3\'',
    length: 20,
    gcPercent: 55.0,
    tmCalculated: 60.8,
    tmOrigin: 'CALCULATED',
    recommendedAnnealing: 60.0,
    annealingOrigin: 'REFERENCE',
    sourceDocument: 'Protocolo de Referencia Bio-Mol GAPDH-01 (Demo Data)',
    targetGene: 'GAPDH Humano',
  },
  {
    id: 'primer_c_16s_fwd',
    name: 'Primer C (16S Universal 27F)',
    direction: 'forward',
    sequence: '5\'-AGAGTTTGATCMTGGCTCAG-3\'',
    length: 20,
    gcPercent: 52.5,
    tmCalculated: 56.4,
    tmOrigin: 'CALCULATED',
    recommendedAnnealing: 54.0,
    annealingOrigin: 'REFERENCE',
    sourceDocument: 'Microbiology Standard PCR Protocol 16S-Bact (Demo Data)',
    targetGene: '16S rRNA Bacteriano',
  },
  {
    id: 'primer_d_16s_rev',
    name: 'Primer D (16S Universal 1492R)',
    direction: 'reverse',
    sequence: '5\'-GGTTACCTTGTTACGACTT-3\'',
    length: 19,
    gcPercent: 42.1,
    tmCalculated: 54.2,
    tmOrigin: 'CALCULATED',
    recommendedAnnealing: 54.0,
    annealingOrigin: 'REFERENCE',
    sourceDocument: 'Microbiology Standard PCR Protocol 16S-Bact (Demo Data)',
    targetGene: '16S rRNA Bacteriano',
  },
  {
    id: 'primer_e_actb_fwd',
    name: 'Primer E (Beta-Actina Fwd)',
    direction: 'forward',
    sequence: '5\'-CATGTACGTTGCTATCCAGGC-3\'',
    length: 21,
    gcPercent: 52.4,
    tmCalculated: 62.0,
    tmOrigin: 'CALCULATED',
    recommendedAnnealing: 61.0,
    annealingOrigin: 'REFERENCE',
    sourceDocument: 'Cell Biology Reference Primers ACTB-Hum (Demo Data)',
    targetGene: 'ACTB Humano',
  },
  {
    id: 'primer_f_actb_rev',
    name: 'Primer F (Beta-Actina Rev)',
    direction: 'reverse',
    sequence: '5\'-CTCCTTAATGTCACGCACGAT-3\'',
    length: 21,
    gcPercent: 47.6,
    tmCalculated: 61.4,
    tmOrigin: 'CALCULATED',
    recommendedAnnealing: 61.0,
    annealingOrigin: 'REFERENCE',
    sourceDocument: 'Cell Biology Reference Primers ACTB-Hum (Demo Data)',
    targetGene: 'ACTB Humano',
  },
];

export const DEMO_POLYMERASES: Polymerase[] = [
  {
    id: 'poly_taq_std',
    name: 'Taq DNA Polimerasa Estándar (Recombinante)',
    manufacturer: 'BioTech Reagents Corp.',
    extensionRateSecPerKb: 60, // 60s per kb (1 kb/min)
    fidelityRatioVsTaq: 1.0,
    hasProofreading: false,
    optimalExtensionTemp: 72,
    initialActivationSec: 180, // 3 min normal denaturation
    recommendedDenatTemp: 95,
    sourceOrigin: 'REFERENCE',
    sourceDocument: 'Ficha Técnica Fabricante Taq Recombinant v2.4 (Demo Data)',
  },
  {
    id: 'poly_q5_hifi',
    name: 'Q5 High-Fidelity DNA Polimerasa',
    manufacturer: 'Genomix Life Sciences',
    extensionRateSecPerKb: 30, // 30s per kb (fast extension)
    fidelityRatioVsTaq: 100.0,
    hasProofreading: true, // 3'->5' exonuclease
    optimalExtensionTemp: 72,
    initialActivationSec: 30, // 30s initial denaturation
    recommendedDenatTemp: 98, // Requires 98°C for denaturation
    sourceOrigin: 'REFERENCE',
    sourceDocument: 'Q5 High-Fidelity Manual Técnico Rev 4 (Demo Data)',
  },
  {
    id: 'poly_hotstart_taq',
    name: 'Hot-Start Taq Polimerasa (Químicamente Modificada)',
    manufacturer: 'AmpTech Diagnostics',
    extensionRateSecPerKb: 60,
    fidelityRatioVsTaq: 1.0,
    hasProofreading: false,
    optimalExtensionTemp: 72,
    initialActivationSec: 600, // 10 min required to release chemical blocking
    recommendedDenatTemp: 95,
    sourceOrigin: 'REFERENCE',
    sourceDocument: 'HotStart MasterMix Technical Manual v1.8 (Demo Data)',
  },
  {
    id: 'poly_pfu_proof',
    name: 'Pfu Polimerasa con Corrección de Pruebas',
    manufacturer: 'Pyrococcus BioTools',
    extensionRateSecPerKb: 120, // 2 min per kb (slower)
    fidelityRatioVsTaq: 12.0,
    hasProofreading: true,
    optimalExtensionTemp: 72,
    initialActivationSec: 180,
    recommendedDenatTemp: 95,
    sourceOrigin: 'REFERENCE',
    sourceDocument: 'Pfu Proofreading Polymerase Protocol (Demo Data)',
  },
];

export const DEMO_BUFFERS: BufferReagent[] = [
  {
    id: 'buf_taq_std_10x',
    name: 'Buffer Estándar 10X Taq (15 mM MgCl2)',
    manufacturer: 'BioTech Reagents Corp.',
    mgConcentrationMm: 1.5, // at 1X
    hasGcEnhancer: false,
    recommendedUse: 'PCR estándar, genotipado, detección de presencia/ausencia',
    sourceOrigin: 'REFERENCE',
  },
  {
    id: 'buf_q5_reaction_5x',
    name: 'Buffer de Reacción Q5 5X (con Mg2+ 2.0 mM)',
    manufacturer: 'Genomix Life Sciences',
    mgConcentrationMm: 2.0,
    hasGcEnhancer: false,
    recommendedUse: 'Clonación de alta fidelidad, secuenciación previa NGS',
    sourceOrigin: 'REFERENCE',
  },
  {
    id: 'buf_gc_enhancer_10x',
    name: 'Buffer GC-Rich con Potenciador Iso-osmótico',
    manufacturer: 'BioTech Reagents Corp.',
    mgConcentrationMm: 2.0,
    hasGcEnhancer: true,
    recommendedUse: 'Plantillas complejas ricas en GC (>65% GC), estructuras secundarias',
    sourceOrigin: 'REFERENCE',
  },
];

export const DEMO_CHEMISTRIES: ChemistryReagent[] = [
  {
    id: 'chem_incolora',
    name: 'Química Incolora Convencional (Agarosa)',
    type: 'incolora',
    description: 'Detección final mediante electroforesis en gel de agarosa con tinción post-PCR.',
    sourceOrigin: 'REFERENCE',
  },
  {
    id: 'chem_sybr_green',
    name: 'SYBR Green I (Fluoróforo Intercalante dsDNA)',
    type: 'intercalante',
    excitationNm: 497,
    emissionNm: 520,
    description: 'Fluorescencia proporcional a la cantidad total de ADN bicatenario generado. Requiere curva de fusión (Melt Curve).',
    sourceOrigin: 'REFERENCE',
  },
  {
    id: 'chem_taqman_probe',
    name: 'Sonda TaqMan Hidrólisis (FAM / TAMRA)',
    type: 'sonda',
    excitationNm: 494,
    emissionNm: 518,
    description: 'Detección específica de secuencia mediante hidrólisis 5\'-3\' exonucleasa. Ideal para cuantificación qPCR multiplex.',
    sourceOrigin: 'REFERENCE',
  },
  {
    id: 'chem_evagreen',
    name: 'EvaGreen High-Resolution Melt',
    type: 'evagreen',
    excitationNm: 500,
    emissionNm: 530,
    description: 'Colorante de menor inhibición enzimática, apto para análisis HRM (High Resolution Melting).',
    sourceOrigin: 'REFERENCE',
  },
];

export const DEFAULT_PROTOCOL_STEPS: ProtocolStep[] = [
  {
    id: 'step_1_init',
    order: 1,
    type: 'inicial',
    temperature: 95,
    durationSeconds: 180, // 3 min
    inCycle: false,
    sourceOrigin: 'REFERENCE',
    sourceReference: 'Protocolo de referencia estándar Taq',
    notes: 'Desnaturalización inicial completa y activación de polimerasa',
  },
  {
    id: 'step_2_denat',
    order: 2,
    type: 'desnaturalizacion',
    temperature: 95,
    durationSeconds: 30,
    cycles: 35,
    inCycle: true,
    sourceOrigin: 'REFERENCE',
    sourceReference: 'Protocolo de referencia BioTech',
    notes: 'Separación de hebras de ADN bicatenario',
  },
  {
    id: 'step_3_anneal',
    order: 3,
    type: 'annealing',
    temperature: 60,
    durationSeconds: 30,
    cycles: 35,
    inCycle: true,
    sourceOrigin: 'CALCULATED',
    sourceReference: 'Calculado a partir de Tm media de los primers (60.5 °C)',
    notes: 'Hibridación específica de primers Fwd y Rev',
  },
  {
    id: 'step_4_ext',
    order: 4,
    type: 'extension',
    temperature: 72,
    durationSeconds: 45,
    cycles: 35,
    inCycle: true,
    sourceOrigin: 'REFERENCE',
    sourceReference: 'Kinetics Taq (60s/kb para 500 bp)',
    notes: 'Polimerización de la nueva cadena 5\' a 3\'',
  },
  {
    id: 'step_5_final_ext',
    order: 5,
    type: 'extension_final',
    temperature: 72,
    durationSeconds: 300, // 5 min
    inCycle: false,
    sourceOrigin: 'REFERENCE',
    sourceReference: 'Protocolo estándar',
    notes: 'Completado de cadenas incompletas y adición de cola poli-A 3\'',
  },
  {
    id: 'step_6_hold',
    order: 6,
    type: 'hold',
    temperature: 4,
    durationSeconds: 0, // indefinite
    inCycle: false,
    sourceOrigin: 'REFERENCE',
    sourceReference: 'Estabilidad de muestra post-reacción',
    notes: 'Mantenimiento a baja temperatura hasta recogida de tubos',
  },
];

export const DEMO_KNOWLEDGE_BASE: KnowledgeItem[] = [
  {
    id: 'k_primer_a',
    category: 'primers',
    name: 'Primer A (Fwd GAPDH)',
    type: 'Oligonucleótido sintético',
    source: 'OligoBase Lab v2.1',
    manufacturer: 'Integrated Oligo Synthesis Inc.',
    updatedYear: 2026,
    version: '1.2.0',
    properties: {
      'Secuencia': '5\'-GGTCTCCTCTGACTTCAACA-3\'',
      'Longitud (nt)': 20,
      'Contenido GC': '50.0 %',
      'Tm Wallace (2(A+T) + 4(G+C))': '60.0 °C',
      'Tm SantaLucia (Vecino Próximo)': '60.2 °C',
      'Riesgo de Dímeros (ΔG)': '-2.1 kcal/mol (Bajo)',
      'Estructura Secundaria': 'Horquilla mínima detectada (Tm < 30°C)',
    },
    rulesAssociated: ['RULE-ANNEALING-004', 'RULE-TM-DELTA-005'],
    referenceProtocols: ['PR-GAPDH-STD-2026', 'PR-QPCR-HOUSEKEEPING'],
    sourceDocument: 'NCBI Gene ID: 2597 / Consensus Primer Design 2026',
    notes: 'Primer validado para expresión génica constitutiva humana.',
  },
  {
    id: 'k_poly_taq',
    category: 'polimerasas',
    name: 'Taq DNA Polimerasa Recombinante',
    type: 'Enzima termoestable (Thermus aquaticus)',
    source: 'BioTech Reference Catalog',
    manufacturer: 'BioTech Reagents Corp.',
    updatedYear: 2026,
    version: '2.4.1',
    properties: {
      'Velocidad de polimerización': '1000 nucleótidos / min (60 s / kb)',
      'Temperatura óptima de extensión': '70–74 °C (nominal 72 °C)',
      'Actividad exonucleasa 5\'->3\'': 'Presente (degradación de sonda TaqMan)',
      'Actividad exonucleasa 3\'->5\' (Proofreading)': 'Ausente (Tasa de error ~2.2x10^-5)',
      'Sobresaliente 3\'': 'Adición de nucleótido A (apto para clonación TA)',
      'Activación inicial requerida': '180 segundos a 95 °C',
    },
    rulesAssociated: ['RULE-EXTENSION-002', 'RULE-DENAT-001'],
    referenceProtocols: ['PR-STD-TAQ-1000BP', 'PR-DIAG-SCREENING'],
    sourceDocument: 'Enzyme Kinetics Manual Sambrook & Russell, 2026 Edition',
    notes: 'Enzima de referencia estándar para PCR diagnóstica y punto final.',
  },
  {
    id: 'k_poly_q5',
    category: 'polimerasas',
    name: 'Q5 High-Fidelity DNA Polimerasa',
    type: 'Quimera de polimerasa hipertermoestable de archaea',
    source: 'Genomix Life Sciences',
    manufacturer: 'Genomix Life Sciences',
    updatedYear: 2026,
    version: '4.0.2',
    properties: {
      'Fidelidad': '100x superior a Taq estándar (error < 1x10^-7)',
      'Velocidad de polimerización': '30 s / kb (2000 nt / min)',
      'Temperatura de desnaturalización': '98 °C (requerida por alta termoestabilidad)',
      'Temperatura óptima de extensión': '72 °C',
      'Actividad exonucleasa 3\'->5\'': 'Presente y activa',
      'Extremos generados': 'Ramos / Blunt ends (sin adenina 3\')',
    },
    rulesAssociated: ['RULE-DENAT-001', 'RULE-EXTENSION-002'],
    referenceProtocols: ['PR-Q5-CLONING-HIGHRES'],
    sourceDocument: 'Genomix Technical Bulletin Q5-2026.1',
  },
  {
    id: 'k_buf_std',
    category: 'buffers',
    name: 'Buffer Estándar 10X Taq (con 15 mM MgCl2)',
    type: 'Solución tampón tamponada Tris-HCl pH 8.3',
    source: 'Fabricante BioTech',
    manufacturer: 'BioTech Reagents Corp.',
    updatedYear: 2026,
    version: '1.0.0',
    properties: {
      'pH a 25 °C': '8.3 ± 0.05',
      'Concentración de Mg2+ a 1X': '1.5 mM',
      'KCl': '50 mM a 1X',
      'Detergente no iónico': '0.1% Triton X-100',
    },
    rulesAssociated: ['RULE-BUFFER-MG-001'],
    referenceProtocols: ['PR-STD-TAQ-1000BP'],
    sourceDocument: 'BioTech Quality Control Certificate Lot #98221',
  },
  {
    id: 'k_chem_sybr',
    category: 'quimicas',
    name: 'Química Fluorimétrica SYBR Green I',
    type: 'Colorante intercalante cianina asimétrica',
    source: 'Molecular Fluorescence Standards',
    manufacturer: 'OptiBio Technologies',
    updatedYear: 2026,
    version: '2.1.0',
    properties: {
      'Longitud de onda de excitación': '497 nm',
      'Longitud de onda de emisión': '520 nm',
      'Aumento de fluorescencia al unirse a dsDNA': '> 1000 veces',
      'Requisito crítico': 'Análisis obligatorio de curva de disociación / fusión',
    },
    rulesAssociated: ['RULE-QPCR-READOUT-001'],
    referenceProtocols: ['PR-QPCR-SYBR-QUANT'],
    sourceDocument: 'qPCR Technical Guideline MIQE Compliant 2026',
  },
  {
    id: 'k_rule_ann_4',
    category: 'reglas',
    name: 'RULE-ANNEALING-004: Cálculo y Rango de Temperatura de Hibridación',
    type: 'Regla de Validación Bioinformática',
    source: 'Consenso Internacional de PCR',
    updatedYear: 2026,
    version: '2.1',
    properties: {
      'Fórmula base': 'Ta = Tm_menor - (2 a 5) °C',
      'Delta Tm máximo admitido': '≤ 4.0 °C entre Fwd y Rev',
      'Rango tolerable': 'Ta nominal ± 2.0 °C',
      'Consecuencia si Ta es muy baja': 'Aparición de amplicones inespecíficos y dímeros',
      'Consecuencia si Ta es muy alta': 'Falta de hibridación y ausencia total de producto',
    },
    rulesAssociated: ['RULE-TM-DELTA-005'],
    referenceProtocols: ['Todos los protocolos de termociclado'],
    sourceDocument: 'Bioinformatic Primer Design Guidelines (BMC Bioinf, 2025/2026)',
  },
  {
    id: 'k_rule_ext_2',
    category: 'reglas',
    name: 'RULE-EXTENSION-002: Tiempo de Extensión según Longitud de Amplicón',
    type: 'Regla Cinética Enzimática',
    source: 'Comité Enzimología Replicativa',
    updatedYear: 2026,
    version: '2.0',
    properties: {
      'Kinetics Taq estándar': '60 s por cada 1000 bp (mínimo 30 s)',
      'Kinetics Q5 / Fast Taq': '30 s por cada 1000 bp (mínimo 15 s)',
      'Kinetics Pfu proofreading': '120 s por cada 1000 bp (mínimo 60 s)',
      'Penalización por tiempo insuficiente': 'Cadenas truncadas, banda difusa en gel',
    },
    rulesAssociated: ['RULE-EXTENSION-002'],
    referenceProtocols: ['Todos los protocolos con Taq / Q5 / Pfu'],
    sourceDocument: 'Methods in Molecular Biology, Vol 1422, PCR Protocols',
  },
  {
    id: 'k_source_sambrook',
    category: 'fuentes',
    name: 'Molecular Cloning: A Laboratory Manual (Sambrook & Russell)',
    type: 'Libro y compendio de referencia internacional',
    source: 'Cold Spring Harbor Laboratory Press',
    updatedYear: 2026,
    version: '5ª Edición Revisada',
    properties: {
      'Capítulo relevante': 'Capítulo 8: In Vitro Amplification of DNA by the PCR',
      'ISBN': '978-1936113422',
      'Tipo de evidencia': 'REFERENCE / EXPERIMENTAL',
      'Cita recomendada': 'Sambrook, J., & Russell, D. W. Molecular Cloning: A Laboratory Manual.',
    },
    rulesAssociated: ['RULE-DENAT-001', 'RULE-ANNEALING-004', 'RULE-EXTENSION-002'],
    referenceProtocols: ['PR-STD-TAQ-1000BP', 'PR-GAPDH-STD-2026'],
    sourceDocument: 'CSHL Press Reference Archives 2026',
  },
];

export const DEMO_TRACEABILITY_ITEMS: Record<string, TraceabilitySource> = {
  'tm_primer_a': {
    parameterName: 'Temperatura de Fusión (Tm Primer A)',
    value: '60.2',
    unit: '°C',
    type: 'CALCULATED',
    sourceName: 'Nearest-Neighbor Thermodynamic Model (SantaLucia 1998)',
    document: 'Algoritmo Termodinámico OligoCalc v4.1',
    manufacturer: 'Integrated Oligo Synthesis Inc.',
    date: '2026-02-14',
    version: '4.1.2',
    method: 'Cálculo termodinámico considerando [Na+] = 50 mM y [Primer] = 200 nM.',
    ruleId: 'RULE-TM-CALC-001',
  },
  'ta_recommended': {
    parameterName: 'Temperatura de Annealing Recomendada',
    value: '60.0',
    unit: '°C',
    type: 'REFERENCE',
    sourceName: 'Protocolo Validado GAPDH-01 BioTech',
    document: 'BioTech Technical Protocol Reference Sheet #GAPDH-778',
    manufacturer: 'BioTech Reagents Corp.',
    date: '2026-01-20',
    version: '2.0',
    method: 'Valor empírico determinado mediante termociclador con gradiente térmico de 54°C a 66°C.',
    ruleId: 'RULE-ANNEALING-004',
  },
  'ta_range': {
    parameterName: 'Rango Operativo de Annealing',
    value: '58–62',
    unit: '°C',
    type: 'EXPERIMENTAL',
    sourceName: 'Gradiente de Temperatura Experimental PCR en Laboratorio',
    document: 'Lab Notebook Entry #2026-03-B / Run Gel 449',
    manufacturer: 'Laboratorio de Biología Molecular Experimental',
    date: '2026-03-11',
    version: '1.0',
    method: 'Evaluación de fluorescencia y electroforesis con bandas limpias observadas entre 58.2°C y 61.9°C.',
    ruleId: 'RULE-ANNEALING-004',
  },
  'ext_time_taq': {
    parameterName: 'Tiempo de Extensión Recomendado',
    value: '45',
    unit: 's',
    type: 'CALCULATED',
    sourceName: 'Kinetics de Polimerasa Taq para Amplicón de 500 bp',
    document: 'Fórmula de Extensión: max(30s, (longitud_bp / 1000) * 60s + 15s margen)',
    manufacturer: 'BioTech Reagents Corp.',
    date: '2026-01-15',
    version: '1.4',
    method: 'Cálculo estandarizado para amplicón de 500 pares de bases a 72°C.',
    ruleId: 'RULE-EXTENSION-002',
  },
  'cycles_count': {
    parameterName: 'Número de Ciclos de Amplificación',
    value: '35',
    unit: 'ciclos',
    type: 'REFERENCE',
    sourceName: 'Compendio Sambrook & Russell',
    document: 'Molecular Cloning Reference Protocols, 5th Ed.',
    date: '2026-01-10',
    version: '5.0',
    method: 'Número estándar de ciclos para detección de copias en rango 10^3 - 10^6 copias iniciales sin efecto meseta inhibitorio.',
    ruleId: 'RULE-CYCLES-001',
  },
};
